### ISSUE TITLE
Problem generating 'net'

### ISSUE THREAD

**Issue by swood-ecology** [Science-for-Nature-and-People/soilc-ca-rangelands#1]
When I execute line 21 of the 'new plotting script' file I get the following error:

`
> net <- graph.data.frame(links, nodes, directed=T)
Error in graph.data.frame(links, nodes, directed = T) : 
  Some vertex names in edge list are not listed in vertex data frame
`

I can't seem to generate the `net` data structure using this code to run through the network mapping functions.

**Comment by dosleger** [comment]
The data should now be updated via the last push. As long as your data link is from the GitHub folder it should work.
