### ISSUE TITLE
No vizParams object

### ISSUE THREAD

**Issue by swood-ecology** [Science-for-Nature-and-People/soilc-ca-rangelands#5]
I tried running the GEE script, but the vizParams object isn't defined in the script. Can you add that code?

**Comment by eoway** [comment]
I just checked both scripts and didn't have a problem plotting with either. Here are the two links again so we can make sure we're working from the same thing. If you're still having trouble, can you specify which link and which line(s)?

https://code.earthengine.google.com/4ba67364df9a0af09447dbb97e330839
https://code.earthengine.google.com/79c169c63a6e3058efadbcdc79df963a

**Comment by swood-ecology** [comment]
Yeah this was probably due to an old script.

**Comment by swood-ecology** [comment]
I added the GEE scripts to the repository.
